### ISSUE TITLE
Unittest fake inputtal

### ISSUE THREAD

**Issue by vattila7811** [Uni-Sopron/prog1-24t-beadando-vattila7811#3]
Szeretnék egy kis segítséget kérni unittesztekkel kapcsolatban, hogy hogyan kell helyesen olyan teszteket írni, ahol a tesztelt függvény vár valamilyen bemenetet?

Betettem egy commitet most amiben a mock modult használom, kérdés, hogy ez így jó-e, vagy van jobb megoldás?

**Comment by oliverosz** [comment]
Néz meg, itt hogy van: https://github.com/Uni-Sopron/prog1-24t-hf01-vattila7811/blob/main/tests/test_1hello.py

**Comment by vattila7811** [comment]
Köszönöm :) 

De akkor az én megoldásom is jó vagy legyen inkább robusztusabb?

**Comment by oliverosz** [comment]
Jó az is.
