### ISSUE TITLE
Text input előre beírt adattal 

### ISSUE THREAD

**Issue by vattila7811** [Uni-Sopron/prog1-24t-beadando-vattila7811#4]
Próbálok egy olyan text inputot összehozni, ami előre kitölti a mezőt az input() számára, hogy ne kelljen begépelni. Sok mindent kipróbáltam, de sajnos nem tudtam működő példát találni. 

az egyik ilyen ígéretes a readline / pyreadline volt:

from pyreadline3 import Readline, rlmain

def rlinput(prompt: str , prefill: str =''):
   readline = Readline()
   readline.insert_text(prefill)
   readline.set_pre_input_hook(lambda : (readline.insert_text(prefill),
                                       readline.redisplay()))
   try:
      return input(prompt)
   finally:
      readline.set_pre_input_hook()
      
de ez sem illeszti be az inputnak a szöveget, pedig a legtöbben ezzel példálóznak. 

Esetleg van valakinek ötlete, hogyan lehetne megvalósítani ilyesmit?

**Comment by vattila7811** [comment]
Közben találtam megoldást (prompt_toolkit). A requirementshez hozzáadom a modult,

**Comment by hegyhati** [comment]
Amikor ilyen kellett nekem, akkor csak siman redirect-eltem vagy pipe-oltam. Az eleg szokott lenni.
